name: Test and Build Plugin

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: yarn test

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: yarn build
